HandyRides/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rides/', include('rides.urls')),
    path('', TemplateView. as_view(template_name="index.html")),
    
]

rides/urls.py
from django.urls import path

from . import views

app_name = 'rides'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create')

]

rides/models.py
from django.db import models

# Create your models here.


class Person(models.Model):
  first_name = models.CharField(max_length=64)
  origination = models.CharField(max_length=64)
  destination_city = models.CharField(max_length=64)
  destination_state = models.CharField(max_length=2)
  date = models.DateField()
  time = models.TimeField()
  age = models.IntegerField(default=0)
  pets = models.BooleanField(default=False)
  seats_available = models.IntegerField(default=0)

rides/forms.py
from django import forms
from .models import Person


class RideForm(forms.Form):
  search = forms.CharField(label='Search term', max_length=64, required=False)


class NewRideForm(forms.ModelForm):
  class Meta:
    model = Person
    exclude = []

rides/views.py
from django.shortcuts import redirect, render

from .models import Person

# relative import of forms
from .forms import RideForm, NewRideForm

# Create your views here.


def index(request):

  context = {}

  if "search" in request.GET:
    search = request.GET["search"]

    context["people"] = Person.objects.filter(
        origination__icontains=search) | Person.objects.filter(destination_city__icontains=search)

  context["form"] = RideForm()
  context["new_ride_form"] = NewRideForm()

  return render(request, "index_view.html", context)


def create(request):
  context = {}
  context["new_ride_form"] = NewRideForm()

  if request.method == "POST":
    new_ride = NewRideForm(request.POST)
    new_ride.save()
    return redirect("/rides")

  return render(request, "create_new.html", context)

rides/templates/create_new.html
<center>
{% block content %}
    <h1 style="font-size:60px;font-family:Comic Sans MS"> Carpool </h1>
    <h2 style="font-size:30px"> carpool.com </h2>
    <h3> Don't be a tool, ride in a carpool </h3>
    <h4 style="font-size:60px">Enter Ride Info Here:</h4>

    <form action="{% url 'rides:create' %}" method="post">
        {% csrf_token %} 
        <table>
            <tr>
                <td>First Name</td>
                <td>{{ new_ride_form.first_name }}</td>
            </tr><tr>  
                <td>Origin City</td>
                <td>{{ new_ride_form.origination }}</td>
            </tr><tr>
                <td>Destination City</td>
                <td>{{ new_ride_form.destination_city }}</td>
            </tr><tr>
                <td>Destination State</td>
                <td>{{ new_ride_form.destination_state }}</td>
            </tr><tr>
                <td>Date</td>
                <td>{{ new_ride_form.date }}</td>
            </tr><tr>
                <td>Time</td>
                <td>{{ new_ride_form.time }}</td>
            </tr><tr>
                <td>Age</td>
                <td>{{ new_ride_form.age }}</td>
            </tr><tr>
                <td>Pets</td>
                <td>{{ new_ride_form.pets }}</td>
            </tr><tr>
                <td>Seats Available</td>
                <td>{{ new_ride_form.seats_available }}</td>
            </tr>
        </table>

        <input type="submit" value="Submit">
    </form>

    {% endblock %}

</center>

rides/templates/index_view.html
{% extends "base.html" %}

{% block content %}
<div class="main"> 
<table>
<style>
      table,
      th,
      td {
        padding: 10px;
        border: 1px solid black;
        border-collapse: collapse;
      }
    </style>
      <tr>
	<th> Name </th>
	<th> Origin </th>
	<th> Destination City </th>
	<th> Destination State </th>
	<th> Date </th>
	<th> Time </th>
  <th> Age </th>
	<th> Taking Pets? </th>
	<th> # Passengers? </th>
      </tr>
      {% for person in people %}
      <tr>
          <td>{{ person.first_name }}</td> 
          <td>{{ person.origination }}</td>
          <td>{{ person.destination_city }}</td> 
          <td>{{ person.destination_state }}</td> 
          <td>{{ person.date }}</td> 
          <td>{{ person.time }}</td> 
          <td>{{ person.age }} </td>
          <td>{{ person.pets }}</td>
          <td>{{ person.seats_available }}</td> 
      </tr>
      {% endfor %} 
  </table>
</div> 

<form action="{% url 'rides:index' %}" method="get">
    {{ form }}
    <input type="submit" value="Submit" onclick="return checkForm(this.parentNode);">
</form>
<h1>Not seeing what you want?</h1>
<h2><a href="http://127.0.0.1:8000/rides/create" style="font-size: 30px; font-style: italic;">Create A Ride Here!</a></h2>

{% endblock %}

templates/base.html
{% load static %}

<html>
<head>
    <script src="{% static 'main.js' %}"></script>
     <link rel="stylesheet" href="{% static 'main.css' %}"/>
</head>
<title> ORF 401: Spring 2020 </title>
<body bgcolor="white" text="black" onload="splash();">
    <center>
      <h1 style="font-size:60px;font-family:Comic Sans MS"> Carpool </h1>
      <h2 style="font-size:30px"> carpool.com </h2>
      <h3> Don't be a tool, ride in a carpool </h3>
      <img src="{% static 'logo1.jpg' %}" alt="Image of logo">

      {% block content %}
      {% endblock %}
    </center>
  </body>
</html>

templates/index.html
{% block content %}


<center>
    <head>
        <style> 
            div {
              width: 100px;
              height: 100px;
              background-color: red;
              position: relative;
              animation-name: example;
              animation-duration: 2s;
              animation-iteration-count: infinite;
            }
            
            @keyframes example {
              0%   {background-color:red; left:-250px; top:0px;}
              25%  {background-color:yellow; left:250px; top:0px;}
              50%  {background-color:blue; left:250px; top:300px;}
              75%  {background-color:green; left:-250px; top:300px;}
              100% {background-color:red; left:-250px; top:0px;}
            }
            </style>
    </head>
    <h1 style="font-size: 100px">Welcome to Carpool!</h1>
    <h2><em> Don't be a tool, ride in a carpool</em></h2>
    <div></div>
    <h3><a href="{% url 'rides:index' %}" style="font-size: 60px">Find A Ride</a> </h3>
    <h4><a href="http://127.0.0.1:8000/rides/create" style="font-size: 40px; font-style: italic;">Create A Ride</a></h4>
</center>

<body style="background-color:gold;"></body>

{% endblock %}